Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # the autogenerated routes, does nt need to be specified, here:

  root to: 'restaurants#index'

  resources :restaurants do

  resources :reviews, only: [:new, :create]

  end
end
